version: "2"
services:
  db:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  app:
    build: .
    command: bundle exec rackup --host 0.0.0.0 -p 4567'
    volumes:
      - ".:/myapp"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: app
      DB_PASSWORD: password
      DB_HOST: db
